import { Inter } from "next/font/google";
import "./globals.css";
import { connectMongoDB } from "../llib/mongodb";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  connectMongoDB();
  return ( 


    <html lang="en">
      <body className={inter.className}>
        <Toaster richColors closeButton theme="dark" position="bottom-left" />
        {children}</body>

    </html>
  );
}
